# Generated by Django 4.1.6 on 2023-02-21 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goal_setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['time_create'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
